# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.2
#
# <auto-generated>
#
# Generated from file `organization_type_dto.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy
from model import common_ice

# Included module com
_M_com = Ice.openModule('com')

# Included module com.jimi
_M_com.jimi = Ice.openModule('com.jimi')

# Included module com.jimi.api
_M_com.jimi.api = Ice.openModule('com.jimi.api')

# Start of module com
__name__ = 'com'

# Start of module com.jimi
__name__ = 'com.jimi'

# Start of module com.jimi.api
__name__ = 'com.jimi.api'

# Start of module com.jimi.api.user
_M_com.jimi.api.user = Ice.openModule('com.jimi.api.user')
__name__ = 'com.jimi.api.user'

# Start of module com.jimi.api.user.organization
_M_com.jimi.api.user.organization = Ice.openModule('com.jimi.api.user.organization')
__name__ = 'com.jimi.api.user.organization'

# Start of module com.jimi.api.user.organization.dto
_M_com.jimi.api.user.organization.dto = Ice.openModule('com.jimi.api.user.organization.dto')
__name__ = 'com.jimi.api.user.organization.dto'

if 'OrganizationTypeInputDTO' not in _M_com.jimi.api.user.organization.dto.__dict__:
    _M_com.jimi.api.user.organization.dto.OrganizationTypeInputDTO = Ice.createTempClass()
    class OrganizationTypeInputDTO(_M_com.jimi.api.BaseInputDTO):
        """
        机构类型服务入参
        @author zhangduanfeng
        @date 2019-08-26
        @since 1.0.0
        Members:
        code -- 机构类型code
        name -- 机构类名称
        """
        def __init__(self, operator=0, platform='', code='', name=''):
            _M_com.jimi.api.BaseInputDTO.__init__(self, operator, platform)
            self.code = code
            self.name = name

        def ice_id(self):
            return '::com::jimi::api::user::organization::dto::OrganizationTypeInputDTO'

        @staticmethod
        def ice_staticId():
            return '::com::jimi::api::user::organization::dto::OrganizationTypeInputDTO'

        def __str__(self):
            return IcePy.stringify(self, _M_com.jimi.api.user.organization.dto._t_OrganizationTypeInputDTO)

        __repr__ = __str__

    _M_com.jimi.api.user.organization.dto._t_OrganizationTypeInputDTO = IcePy.defineValue('::com::jimi::api::user::organization::dto::OrganizationTypeInputDTO', OrganizationTypeInputDTO, -1, (), False, False, _M_com.jimi.api._t_BaseInputDTO, (
        ('code', (), IcePy._t_string, False, 0),
        ('name', (), IcePy._t_string, False, 0)
    ))
    OrganizationTypeInputDTO._ice_type = _M_com.jimi.api.user.organization.dto._t_OrganizationTypeInputDTO

    _M_com.jimi.api.user.organization.dto.OrganizationTypeInputDTO = OrganizationTypeInputDTO
    del OrganizationTypeInputDTO

if 'OrganizationTypeOutputDTO' not in _M_com.jimi.api.user.organization.dto.__dict__:
    _M_com.jimi.api.user.organization.dto.OrganizationTypeOutputDTO = Ice.createTempClass()
    class OrganizationTypeOutputDTO(Ice.Value):
        """
        机构类型服务入参
        @author zhangduanfeng
        @date 2019-08-26
        @since 1.0.0
        Members:
        code -- 机构类型code
        name -- 机构类名称
        """
        def __init__(self, code='', name=''):
            self.code = code
            self.name = name

        def ice_id(self):
            return '::com::jimi::api::user::organization::dto::OrganizationTypeOutputDTO'

        @staticmethod
        def ice_staticId():
            return '::com::jimi::api::user::organization::dto::OrganizationTypeOutputDTO'

        def __str__(self):
            return IcePy.stringify(self, _M_com.jimi.api.user.organization.dto._t_OrganizationTypeOutputDTO)

        __repr__ = __str__

    _M_com.jimi.api.user.organization.dto._t_OrganizationTypeOutputDTO = IcePy.defineValue('::com::jimi::api::user::organization::dto::OrganizationTypeOutputDTO', OrganizationTypeOutputDTO, -1, (), False, False, None, (
        ('code', (), IcePy._t_string, False, 0),
        ('name', (), IcePy._t_string, False, 0)
    ))
    OrganizationTypeOutputDTO._ice_type = _M_com.jimi.api.user.organization.dto._t_OrganizationTypeOutputDTO

    _M_com.jimi.api.user.organization.dto.OrganizationTypeOutputDTO = OrganizationTypeOutputDTO
    del OrganizationTypeOutputDTO

# End of module com.jimi.api.user.organization.dto

__name__ = 'com.jimi.api.user.organization'

# End of module com.jimi.api.user.organization

__name__ = 'com.jimi.api.user'

# End of module com.jimi.api.user

__name__ = 'com.jimi.api'

# End of module com.jimi.api

__name__ = 'com.jimi'

# End of module com.jimi

__name__ = 'com'

# End of module com
