# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.2
#
# <auto-generated>
#
# Generated from file `organization_info_dto.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy
from model import common_ice

# Included module com
_M_com = Ice.openModule('com')

# Included module com.jimi
_M_com.jimi = Ice.openModule('com.jimi')

# Included module com.jimi.api
_M_com.jimi.api = Ice.openModule('com.jimi.api')

# Start of module com
__name__ = 'com'

# Start of module com.jimi
__name__ = 'com.jimi'

# Start of module com.jimi.api
__name__ = 'com.jimi.api'

# Start of module com.jimi.api.user
_M_com.jimi.api.user = Ice.openModule('com.jimi.api.user')
__name__ = 'com.jimi.api.user'

# Start of module com.jimi.api.user.organization
_M_com.jimi.api.user.organization = Ice.openModule('com.jimi.api.user.organization')
__name__ = 'com.jimi.api.user.organization'

# Start of module com.jimi.api.user.organization.dto
_M_com.jimi.api.user.organization.dto = Ice.openModule('com.jimi.api.user.organization.dto')
__name__ = 'com.jimi.api.user.organization.dto'

if 'OrganizationInputDTO' not in _M_com.jimi.api.user.organization.dto.__dict__:
    _M_com.jimi.api.user.organization.dto.OrganizationInputDTO = Ice.createTempClass()
    class OrganizationInputDTO(_M_com.jimi.api.BaseInputDTO):
        """
        机构参数
        @date 2019年8月21日 上午11:27:16
        @author yaojianping
        @version 1.0
        Members:
        oid -- oid，如果是修改
        parent -- 父机构oid
        code -- 机构类型code
        name -- 机构/公司名称
        email -- 邮箱
        contact -- 联系人
        phone -- 手机号
        province -- 省
        city -- 市
        region -- 区
        detail -- 详细地址
        appId -- 机构秘钥
        appSecret -- 机构秘钥
        domain -- 域名
        logo -- logo
        """
        def __init__(self, operator='', platform='', oid='', parent='', code='', name='', email='', contact='', phone='',
                     province='', city='', region='', detail='', appId='', appSecret='', domain='', logo=''):
            _M_com.jimi.api.BaseInputDTO.__init__(self, operator, platform)
            self.oid = oid
            self.parent = parent
            self.code = code
            self.name = name
            self.email = email
            self.contact = contact
            self.phone = phone
            self.province = province
            self.city = city
            self.region = region
            self.detail = detail
            self.appId = appId
            self.appSecret = appSecret
            self.domain = domain
            self.logo = logo

        def ice_id(self):
            return '::com::jimi::api::user::organization::dto::OrganizationInputDTO'

        @staticmethod
        def ice_staticId():
            return '::com::jimi::api::user::organization::dto::OrganizationInputDTO'

        def __str__(self):
            return IcePy.stringify(self, _M_com.jimi.api.user.organization.dto._t_OrganizationInputDTO)

        __repr__ = __str__

    _M_com.jimi.api.user.organization.dto._t_OrganizationInputDTO = IcePy.defineValue('::com::jimi::api::user::organization::dto::OrganizationInputDTO', OrganizationInputDTO, -1, (), False, False, _M_com.jimi.api._t_BaseInputDTO, (
        ('oid', (), IcePy._t_string, False, 0),
        ('parent', (), IcePy._t_string, False, 0),
        ('code', (), IcePy._t_string, False, 0),
        ('name', (), IcePy._t_string, False, 0),
        ('email', (), IcePy._t_string, False, 0),
        ('contact', (), IcePy._t_string, False, 0),
        ('phone', (), IcePy._t_string, False, 0),
        ('province', (), IcePy._t_string, False, 0),
        ('city', (), IcePy._t_string, False, 0),
        ('region', (), IcePy._t_string, False, 0),
        ('detail', (), IcePy._t_string, False, 0),
        ('appId', (), IcePy._t_string, False, 0),
        ('appSecret', (), IcePy._t_string, False, 0),
        ('domain', (), IcePy._t_string, False, 0),
        ('logo', (), IcePy._t_string, False, 0)
    ))
    OrganizationInputDTO._ice_type = _M_com.jimi.api.user.organization.dto._t_OrganizationInputDTO

    _M_com.jimi.api.user.organization.dto.OrganizationInputDTO = OrganizationInputDTO
    del OrganizationInputDTO

if 'OrganizationOutputDTO' not in _M_com.jimi.api.user.organization.dto.__dict__:
    _M_com.jimi.api.user.organization.dto.OrganizationOutputDTO = Ice.createTempClass()
    class OrganizationOutputDTO(_M_com.jimi.api.BaseOutputDTO):
        """
        机构基本信息
        @date 2019年8月21日 上午11:27:16
        @author yaojianping
        @version 1.0
        Members:
        oid -- 机构Id
        name -- 机构/公司名称
        type -- 机构类型
        parent -- 父id
        hasChild -- 是否有下级
        """
        def __init__(self, oid='', name='', type='', parent='', hasChild=False):
            _M_com.jimi.api.BaseOutputDTO.__init__(self)
            self.oid = oid
            self.name = name
            self.type = type
            self.parent = parent
            self.hasChild = hasChild

        def ice_id(self):
            return '::com::jimi::api::user::organization::dto::OrganizationOutputDTO'

        @staticmethod
        def ice_staticId():
            return '::com::jimi::api::user::organization::dto::OrganizationOutputDTO'

        def __str__(self):
            return IcePy.stringify(self, _M_com.jimi.api.user.organization.dto._t_OrganizationOutputDTO)

        __repr__ = __str__

    _M_com.jimi.api.user.organization.dto._t_OrganizationOutputDTO = IcePy.defineValue('::com::jimi::api::user::organization::dto::OrganizationOutputDTO', OrganizationOutputDTO, -1, (), False, False, _M_com.jimi.api._t_BaseOutputDTO, (
        ('oid', (), IcePy._t_string, False, 0),
        ('name', (), IcePy._t_string, False, 0),
        ('type', (), IcePy._t_string, False, 0),
        ('parent', (), IcePy._t_string, False, 0),
        ('hasChild', (), IcePy._t_bool, False, 0)
    ))
    OrganizationOutputDTO._ice_type = _M_com.jimi.api.user.organization.dto._t_OrganizationOutputDTO

    _M_com.jimi.api.user.organization.dto.OrganizationOutputDTO = OrganizationOutputDTO
    del OrganizationOutputDTO

# End of module com.jimi.api.user.organization.dto

__name__ = 'com.jimi.api.user.organization'

# End of module com.jimi.api.user.organization

__name__ = 'com.jimi.api.user'

# End of module com.jimi.api.user

__name__ = 'com.jimi.api'

# End of module com.jimi.api

__name__ = 'com.jimi'

# End of module com.jimi

__name__ = 'com'

# End of module com
