# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.2
#
# <auto-generated>
#
# Generated from file `organization_account_dto.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy
from model import common_ice

# Included module com
_M_com = Ice.openModule('com')

# Included module com.jimi
_M_com.jimi = Ice.openModule('com.jimi')

# Included module com.jimi.api
_M_com.jimi.api = Ice.openModule('com.jimi.api')

# Start of module com
__name__ = 'com'

# Start of module com.jimi
__name__ = 'com.jimi'

# Start of module com.jimi.api
__name__ = 'com.jimi.api'

# Start of module com.jimi.api.user
_M_com.jimi.api.user = Ice.openModule('com.jimi.api.user')
__name__ = 'com.jimi.api.user'

# Start of module com.jimi.api.user.organization
_M_com.jimi.api.user.organization = Ice.openModule('com.jimi.api.user.organization')
__name__ = 'com.jimi.api.user.organization'

# Start of module com.jimi.api.user.organization.dto
_M_com.jimi.api.user.organization.dto = Ice.openModule('com.jimi.api.user.organization.dto')
__name__ = 'com.jimi.api.user.organization.dto'

if 'AccountOutputDTO' not in _M_com.jimi.api.user.organization.dto.__dict__:
    _M_com.jimi.api.user.organization.dto.AccountOutputDTO = Ice.createTempClass()
    class AccountOutputDTO(_M_com.jimi.api.BaseOutputDTO):
        """
        账号基本信息
        @date 2019年8月21日 上午11:27:37
        @author yaojianping
        @version 1.0
        Members:
        uid -- 账号id
        userName -- 用户名(可用于登录)
        nickName -- 昵称
        phone -- 手机号(可用于登录)
        email -- 邮箱(可用于登录)
        """
        def __init__(self, uid='', userName='', nickName='', phone='', email=''):
            _M_com.jimi.api.BaseOutputDTO.__init__(self)
            self.uid = uid
            self.userName = userName
            self.nickName = nickName
            self.phone = phone
            self.email = email

        def ice_id(self):
            return '::com::jimi::api::user::organization::dto::AccountOutputDTO'

        @staticmethod
        def ice_staticId():
            return '::com::jimi::api::user::organization::dto::AccountOutputDTO'

        def __str__(self):
            return IcePy.stringify(self, _M_com.jimi.api.user.organization.dto._t_AccountOutputDTO)

        __repr__ = __str__

    _M_com.jimi.api.user.organization.dto._t_AccountOutputDTO = IcePy.defineValue('::com::jimi::api::user::organization::dto::AccountOutputDTO', AccountOutputDTO, -1, (), False, False, _M_com.jimi.api._t_BaseOutputDTO, (
        ('uid', (), IcePy._t_string, False, 0),
        ('userName', (), IcePy._t_string, False, 0),
        ('nickName', (), IcePy._t_string, False, 0),
        ('phone', (), IcePy._t_string, False, 0),
        ('email', (), IcePy._t_string, False, 0)
    ))
    AccountOutputDTO._ice_type = _M_com.jimi.api.user.organization.dto._t_AccountOutputDTO

    _M_com.jimi.api.user.organization.dto.AccountOutputDTO = AccountOutputDTO
    del AccountOutputDTO

if 'AccountInputDTO' not in _M_com.jimi.api.user.organization.dto.__dict__:
    _M_com.jimi.api.user.organization.dto.AccountInputDTO = Ice.createTempClass()
    class AccountInputDTO(_M_com.jimi.api.BaseInputDTO):
        """
        添加账号输入
        @date 2019年8月21日 上午11:27:37
        @author yaojianping
        @version 1.0
        Members:
        uid -- 账号id
        oid -- 机构id
        userName -- 用户名(可用于登录)
        password -- 密码
        nickName -- 昵称
        phone -- 手机号(可用于登录)
        email -- 邮箱(可用于登录)
        """
        def __init__(self, operator='', platform='', uid='', oid='', userName='', password='', nickName='', phone='', email=''):
            _M_com.jimi.api.BaseInputDTO.__init__(self, operator, platform)
            self.uid = uid
            self.oid = oid
            self.userName = userName
            self.password = password
            self.nickName = nickName
            self.phone = phone
            self.email = email

        def ice_id(self):
            return '::com::jimi::api::user::organization::dto::AccountInputDTO'

        @staticmethod
        def ice_staticId():
            return '::com::jimi::api::user::organization::dto::AccountInputDTO'

        def __str__(self):
            return IcePy.stringify(self, _M_com.jimi.api.user.organization.dto._t_AccountInputDTO)

        __repr__ = __str__

    _M_com.jimi.api.user.organization.dto._t_AccountInputDTO = IcePy.defineValue('::com::jimi::api::user::organization::dto::AccountInputDTO', AccountInputDTO, -1, (), False, False, _M_com.jimi.api._t_BaseInputDTO, (
        ('uid', (), IcePy._t_string, False, 0),
        ('oid', (), IcePy._t_string, False, 0),
        ('userName', (), IcePy._t_string, False, 0),
        ('password', (), IcePy._t_string, False, 0),
        ('nickName', (), IcePy._t_string, False, 0),
        ('phone', (), IcePy._t_string, False, 0),
        ('email', (), IcePy._t_string, False, 0)
    ))
    AccountInputDTO._ice_type = _M_com.jimi.api.user.organization.dto._t_AccountInputDTO

    _M_com.jimi.api.user.organization.dto.AccountInputDTO = AccountInputDTO
    del AccountInputDTO

if 'AccountPageInputDTO' not in _M_com.jimi.api.user.organization.dto.__dict__:
    _M_com.jimi.api.user.organization.dto.AccountPageInputDTO = Ice.createTempClass()
    class AccountPageInputDTO(_M_com.jimi.api.BasePageInputDTO):
        """
        账号基本信息
        @date 2019年8月21日 上午11:27:37
        @author yaojianping
        @version 1.0
        Members:
        oid -- 机构id
        """
        def __init__(self, operator='', platform='', page=1, size=20, oid=''):
            _M_com.jimi.api.BasePageInputDTO.__init__(self, operator, platform, page, size)
            self.oid = oid

        def ice_id(self):
            return '::com::jimi::api::user::organization::dto::AccountPageInputDTO'

        @staticmethod
        def ice_staticId():
            return '::com::jimi::api::user::organization::dto::AccountPageInputDTO'

        def __str__(self):
            return IcePy.stringify(self, _M_com.jimi.api.user.organization.dto._t_AccountPageInputDTO)

        __repr__ = __str__

    _M_com.jimi.api.user.organization.dto._t_AccountPageInputDTO = IcePy.defineValue('::com::jimi::api::user::organization::dto::AccountPageInputDTO', AccountPageInputDTO, -1, (), False, False, _M_com.jimi.api._t_BasePageInputDTO, (('oid', (), IcePy._t_string, False, 0),))
    AccountPageInputDTO._ice_type = _M_com.jimi.api.user.organization.dto._t_AccountPageInputDTO

    _M_com.jimi.api.user.organization.dto.AccountPageInputDTO = AccountPageInputDTO
    del AccountPageInputDTO

if '_t_AccountList' not in _M_com.jimi.api.user.organization.dto.__dict__:
    _M_com.jimi.api.user.organization.dto._t_AccountList = IcePy.defineSequence('::com::jimi::api::user::organization::dto::AccountList', (), _M_com.jimi.api.user.organization.dto._t_AccountOutputDTO)

if 'AccountPageOutputDTO' not in _M_com.jimi.api.user.organization.dto.__dict__:
    _M_com.jimi.api.user.organization.dto.AccountPageOutputDTO = Ice.createTempClass()
    class AccountPageOutputDTO(_M_com.jimi.api.BasePageOutputDTO):
        """
        账号基本信息
        @date 2019年8月21日 上午11:27:37
        @author yaojianping
        @version 1.0
        Members:
        data -- 分页结果
        """
        def __init__(self, size=0, page=0, totalPage=0, totalSize=0, data=None):
            _M_com.jimi.api.BasePageOutputDTO.__init__(self, size, page, totalPage, totalSize)
            self.data = data

        def ice_id(self):
            return '::com::jimi::api::user::organization::dto::AccountPageOutputDTO'

        @staticmethod
        def ice_staticId():
            return '::com::jimi::api::user::organization::dto::AccountPageOutputDTO'

        def __str__(self):
            return IcePy.stringify(self, _M_com.jimi.api.user.organization.dto._t_AccountPageOutputDTO)

        __repr__ = __str__

    _M_com.jimi.api.user.organization.dto._t_AccountPageOutputDTO = IcePy.declareValue('::com::jimi::api::user::organization::dto::AccountPageOutputDTO')

    _M_com.jimi.api.user.organization.dto._t_AccountPageOutputDTO = IcePy.defineValue('::com::jimi::api::user::organization::dto::AccountPageOutputDTO', AccountPageOutputDTO, -1, (), False, False, _M_com.jimi.api._t_BasePageOutputDTO, (('data', (), _M_com.jimi.api.user.organization.dto._t_AccountList, False, 0),))
    AccountPageOutputDTO._ice_type = _M_com.jimi.api.user.organization.dto._t_AccountPageOutputDTO

    _M_com.jimi.api.user.organization.dto.AccountPageOutputDTO = AccountPageOutputDTO
    del AccountPageOutputDTO

# End of module com.jimi.api.user.organization.dto

__name__ = 'com.jimi.api.user.organization'

# End of module com.jimi.api.user.organization

__name__ = 'com.jimi.api.user'

# End of module com.jimi.api.user

__name__ = 'com.jimi.api'

# End of module com.jimi.api

__name__ = 'com.jimi'

# End of module com.jimi

__name__ = 'com'

# End of module com
