# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("com.jimi.platform")

# Modules:
import platform_ice
import platform-header_ice
import organiz_ice
import organiz_common_ice

# Submodules:
from . import user
