# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("com.jimi.api.user")

# Modules:
import platform_ice
import platform_dto_ice
import organization_type_ice
import organization_type_dto_ice

# Submodules:
from . import system
from . import organization
