# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("com.jimi")

# Modules:
import platform_ice
import platform_dto_ice
import common_ice
import organization_type_ice
import organization_type_dto_ice
import appuser_ice
import appuser_dto_ice
import organization_account_ice
import organization_account_dto_ice
import organization_info_ice
import organization_info_dto_ice
import organization_role_ice
import organization_role_dto_ice
import system_member_ice
import system_member_dto_ice
import uid_ice

# Submodules:
from . import api
